In [31]:
import numpy as np
import plotly.graph_objects as go
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel, WhiteKernel

import sys
import os
# 使用当前工作目录
project_root = os.path.dirname(os.getcwd())  # 获取当前目录的父目录
sys.path.insert(0, project_root)
from util.methods import assign_variances  # 若未使用，可保留以兼容后续逻辑

seed = 42
np.random.seed(seed)

# 生成10个来自 N(80, 10) 的随机数
Basic = np.random.normal(80, 5, 16)
Patterns = np.random.normal(78, 5, 6)
Contact = np.random.normal(75, 5, 15)
Instrument = np.random.normal(75, 5, 12)
Basic_formation = np.random.normal(78, 5, 21)
Tactical_formation = np.random.normal(72, 5, 9)
Low_level = np.random.normal(72, 5, 8)
Four_Ship_formation = np.random.normal(72, 5, 8)
CAF_introduction = np.random.normal(68, 5, 22)
MAF_introduction = np.random.normal(70, 5, 12)
mu_data = [Basic,Patterns,Contact,Instrument,Basic_formation,Tactical_formation,Low_level,Four_Ship_formation,CAF_introduction,MAF_introduction]

In [32]:
mu_data

[array([82.48357077, 79.30867849, 83.23844269, 87.61514928, 78.82923313,
        78.82931522, 87.89606408, 83.83717365, 77.65262807, 82.71280022,
        77.68291154, 77.67135123, 81.20981136, 70.43359878, 71.37541084,
        77.18856235]),
 array([72.9358444 , 79.57123666, 73.45987962, 70.93848149, 85.32824384,
        76.8711185 ]),
 array([75.33764102, 67.87625907, 72.27808638, 75.55461295, 69.24503211,
        76.87849009, 71.99680655, 73.54153125, 71.99146694, 84.26139092,
        74.93251388, 69.71144536, 79.11272456, 68.89578175, 76.04431798]),
 array([65.20164938, 68.35906976, 75.98430618, 78.6923329 , 75.85684141,
        74.42175859, 73.49448152, 67.60739005, 71.40077896, 72.69680615,
        80.28561113, 76.71809145]),
 array([69.18479922, 79.62041985, 76.0745886 , 74.61539   , 81.05838144,
        83.15499761, 82.6564006 , 73.80391238, 76.45393812, 79.65631716,
        82.87772564, 75.60412881, 77.07170512, 72.46832513, 72.01896688,
        82.06262911, 84.78120014, 77.639